version: "3.1"
services:
  server:
    image: server
    build: ./
    ports:
      - "8080:8000"
    env_file:
      - ./service.env
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./db.env

volumes:
  pg_data: